language: clojure
lein: lein2
script: lein2 check
jdk:
  - oraclejdk8
sudo: false

env:
  global:
    - OC_BINARY_FOLDER=./target/uberjar
    - OC_BUILD_CONFIG_NAME=botunfurl

after_success: ./build-uberjar.sh ; curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/oc-deploy.sh | bash
