language: clojure
lein: lein2
script: lein2 do check, midje, uberjar
jdk:
  - oraclejdk8
sudo: false

env:
  global:
    - OC_BINARY_FOLDER=./target
    - OC_BUILD_CONFIG_NAME=botunfurl

after_success: curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/oc-deploy.sh | bash
