# Prerequisites:
# ./certs folder exists and contains bot user cert and truststore
# ./config.edn file exists
# For more details, check README.md

version: '2'
services:
 bot-unfurl:
   restart: always
   build: .
   volumes:
    - .:/etc/opt/bot-unfurl:ro
